### PR TITLE
Fix min and max errors on windows

### LINKED ISSUE #131: Installation fails (max is not a template of std among others)
I tried to install `ttystudio`, but I got this error message:

```
R:\>npm install ttystudio -g
-
> pty.js@0.3.0 install C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty.js
> node-gyp rebuild


C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Agent.cc
  AgentAssert.cc
  ConsoleInput.cc
  Coord.cc
  EventLoop.cc
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C2039: 'max' : is not a member  of 'std' [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\ pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C3861: 'max': identifier not f ound [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty.j s\build\deps\winpty\winpty-agent.vcxproj]
  NamedPipe.cc
  SmallRect.cc
  Terminal.cc
  Win32Console.cc
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C2039: 'min' : is not a membe r of 'std' [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules \pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C3861: 'min': identifier not
found [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty. js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C2039: 'min' : is not a membe r of 'std' [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules \pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C3861: 'min': identifier not
found [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty. js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C2039: 'min' : is not a membe r of 'std' [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules \pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C3861: 'min': identifier not
found [C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty. js\build\deps\winpty\winpty-agent.vcxproj]
  main.cc
  DebugClient.cc
  winpty.cc
  DebugClient.cc
  win_delay_load_hook.c
     Creating library C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\no
  de_modules\pty.js\build\Release\winpty.lib and object C:\Users\User\AppData\Roa
  ming\npm\node_modules\ttystudio\node_modules\pty.js\build\Release\winpty.exp
  Generating code
  Finished generating code
  winpty.vcxproj -> C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node
  _modules\pty.js\build\Release\\winpty.dll
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd C:\Users\User\AppData\Roaming\npm\node_modules\ttystudio\node_modules\pty.js
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ttystudio" "-g"
npm ERR! node v3.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     R:\npm-debug.log
```

Apparently you might need to update NAN to version 2. See nodejs/node-gyp#701 for more information on that - I don't understand it :)

### PR DESCRIPTION
**Pull request by iiegor**
The latest commit that was made on peters/winpty fix this issues, so updating winpty will be fine (please remember publishing the pkg when you merge, thanks).

Fixes #131

### CODE REVIEW

**Comment by BenasPaulikas** [comment]
How can I make this work on my end ?

**Comment by iiegor** [comment]
@BenasPaulikas at the moment you can do ``npm install ptyw.js``

**Comment by BenasPaulikas** [comment]
@iiegor Osom. It's finally compiling. :+1: When it will be pushed to normal pty.js git ?

**Comment by BenasPaulikas** [comment]
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 14, got 46.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\wamp\www\ml\node_modules\ptyw.js\lib\pty.js:9:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by BenasPaulikas** [comment]
On windows version .on('data') doesn't works though child_process on('data') returns all text

**Comment by iiegor** [comment]
@BenasPaulikas Strange... must work :confused: Check [this](https://github.com/black-screen/black-screen/blob/master/src/CommandExecutor.ts), uses ptyw.js and the data event works well on windows.

**Comment by BenasPaulikas** [comment]
@iiegor Apparently launching .exe gives no data emmitter, however if I launch .bat file which launch .exe file it's working good. Strange..

**Comment by BenasPaulikas** [comment]
@iiegor Will ptyw.js and pty.js will be merged someday ?

**Comment by iiegor** [comment]
@BenasPaulikas My apologies for closing this but this PR was opened the 10 of Sept and the author was active at that time and there wasn't any comment or interest from him in merging this.

**Comment by BenasPaulikas** [comment]
@iiegor Strange, why it's being ignored? I saw lots of issues lately regarding this fix

**Comment by darkf** [comment]
@chjj I hate to be blunt like this, but are you absolutely daft? This is an essential fix and you straight up ignored it. Are you even maintaining this anymore?

It doesn't build with VS2015 either. You should think about updating winpty to a version not **3 fucking years old**, maybe?

Come on, @chjj. You have time to maintain this instead of writing useless crap like browser terminals which uses this in the first place.

**Comment by BenasPaulikas** [comment]
lol

**Comment by darkf** [comment]
Nevermind, ptyw.js is an updated fork ( https://github.com/iiegor/ptyw.js )

@BenasPaulikas Looks like this will never be merged, author is too busy writing browser terminals in San Francisco. =P

**Pull request closed without merging**
