### PR TITLE
Fix the osx build fixing commit

### PR DESCRIPTION
**Pull request by carlosbaraza**
Hi @chjj,

The last commit to fix the build did not actually work for me so I submit you a version that is correctly working for me.

Thank you for your fix,
Carlos.

### CODE REVIEW

**Comment by jedverity** [comment]
+1

**Comment by chjj** [comment]
Don't know why my fix didn't work for others. This one works for me too. Merging.

**Comment by carlosbaraza** [comment]
In my case at least, the problem was that this header file was not available in a SDK folder but directly in `/usr/include/util.h`. For that reason, the pipe to `grep SDK` was not getting a correct folder. Instead of guessing the correct folder I just looked in the possible folders for the util.h to get a folder with that file.

Thank you for the merge.

**Comment by chjj** [comment]
See #104. This also worked for me.

**Pull request merged**
