### PR TITLE
update dependency nan@2.0.5 to nan@2.3.5

### PR DESCRIPTION
**Pull request by y13i**
Looks like nan@2.0.5 has a problem with recent versions of V8.

### CODE REVIEW

**Comment by LaKing** [comment]
This would fix many issues if published.

**Comment by CrashyBang** [comment]
:+1:

**Comment by ivankravets** [comment]
Also, would be good to update to the latest WinPty 0.4.0. Here are the build logs:

1. NAN 2.3.5 and WinPty 0.4.0 http://pastebin.com/DJrUC22k
2. NAN 2.3.5 and WinPty 0.2.0 http://pastebin.com/wAgPea51

**Comment by ivankravets** [comment]
@chjj did you test this PR? I see that you have released new version 0.3.1. I made [a few tests](https://github.com/chjj/pty.js/pull/159#issuecomment-223926975) and 2.3.5 NAN doesn't compatible with obsolete WinPty.

It seems that this package now is broken for Windows users.

See log: http://pastebin.com/UQQJZ0HE

**Comment by ivankravets** [comment]
In this case, need to update WinPty to 0.4.0 and use new WinPty API

**Pull request merged**
